#!/usr/bin/env python3
"""Cardboard post-release torture harness.

This runner intentionally separates two concerns:
1. TCP connection churn against the Minecraft listener.
2. Process/log health gates for the running server.

Raw TCP clients are NOT Minecraft protocol bots. They exercise accept/connect/
disconnect paths only. Bukkit/Paper API stress is generated by the companion
CardboardTorture plugin in tools/torture/plugin.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import re
import signal
import sys
import time
import tomllib
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

ERROR_RE = re.compile(
    r"(?:\bERROR\b|\bFATAL\b|Exception|Error:|OutOfMemoryError|"
    r"StackOverflowError|ConcurrentModificationException|Watchdog)",
    re.IGNORECASE,
)


@dataclass
class Counters:
    attempts: int = 0
    connected: int = 0
    connect_failures: int = 0
    unexpected_disconnects: int = 0
    active: int = 0
    peak_active: int = 0


@dataclass
class Sample:
    elapsed_seconds: float
    active_connections: int
    rss_mb: float | None = None


@dataclass
class Result:
    scenario: str
    started_at: str
    duration_seconds: float
    target: str
    counters: Counters
    samples: list[Sample] = field(default_factory=list)
    rss_start_mb: float | None = None
    rss_end_mb: float | None = None
    rss_growth_mb: float | None = None
    error_lines: list[str] = field(default_factory=list)
    gates: dict[str, dict[str, Any]] = field(default_factory=dict)
    passed: bool = False


def load_config(path: Path, scenario: str) -> tuple[dict[str, Any], dict[str, Any]]:
    with path.open("rb") as fh:
        config = tomllib.load(fh)
    if scenario not in config:
        raise SystemExit(f"Unknown scenario: {scenario}")
    merged = dict(config.get("defaults", {}))
    merged.update(config[scenario])
    return merged, dict(config.get("limits", {}))


def read_rss_mb(pid: int | None) -> float | None:
    if pid is None:
        return None
    status = Path(f"/proc/{pid}/status")
    try:
        for line in status.read_text(encoding="utf-8", errors="replace").splitlines():
            if line.startswith("VmRSS:"):
                kb = int(line.split()[1])
                return kb / 1024.0
    except (FileNotFoundError, PermissionError, ProcessLookupError, ValueError):
        return None
    return None


def read_new_log_errors(path: Path | None, offset: int) -> tuple[int, list[str]]:
    if path is None or not path.exists():
        return offset, []
    try:
        with path.open("r", encoding="utf-8", errors="replace") as fh:
            fh.seek(offset)
            lines = fh.readlines()
            new_offset = fh.tell()
    except OSError:
        return offset, []
    errors = [line.rstrip() for line in lines if ERROR_RE.search(line)]
    return new_offset, errors


async def tcp_worker(
    worker_id: int,
    host: str,
    port: int,
    connect_timeout: float,
    reconnect: bool,
    stop: asyncio.Event,
    counters: Counters,
) -> None:
    del worker_id
    while not stop.is_set():
        writer: asyncio.StreamWriter | None = None
        try:
            counters.attempts += 1
            _, writer = await asyncio.wait_for(
                asyncio.open_connection(host, port), timeout=connect_timeout
            )
            counters.connected += 1
            counters.active += 1
            counters.peak_active = max(counters.peak_active, counters.active)

            while not stop.is_set():
                await asyncio.sleep(0.25)
                if writer.is_closing():
                    if not stop.is_set():
                        counters.unexpected_disconnects += 1
                    break
        except (ConnectionError, TimeoutError, OSError, asyncio.TimeoutError):
            counters.connect_failures += 1
        finally:
            if writer is not None:
                if counters.active > 0:
                    counters.active -= 1
                writer.close()
                try:
                    await writer.wait_closed()
                except (ConnectionError, OSError):
                    pass

        if not reconnect or stop.is_set():
            return
        await asyncio.sleep(0.2)


async def run(args: argparse.Namespace) -> int:
    config, limits = load_config(args.config, args.scenario)
    host = args.host or str(config["host"])
    port = args.port or int(config["port"])
    duration = args.duration or float(config["duration_seconds"])
    count = args.connections or int(config["connections"])
    rate = args.rate or float(config["connect_rate_per_second"])
    timeout = float(config.get("connect_timeout_seconds", 3))
    reconnect = bool(config.get("reconnect", True))
    sample_interval = float(config.get("sample_interval_seconds", 5))

    if count < 1 or rate <= 0 or duration <= 0:
        raise SystemExit("connections, rate, and duration must be positive")

    started_wall = datetime.now(timezone.utc).isoformat()
    started = time.monotonic()
    counters = Counters()
    samples: list[Sample] = []
    errors: list[str] = []
    log_offset = args.log.stat().st_size if args.log and args.log.exists() else 0
    rss_start = read_rss_mb(args.pid)
    stop = asyncio.Event()

    loop = asyncio.get_running_loop()
    for sig in (signal.SIGINT, signal.SIGTERM):
        try:
            loop.add_signal_handler(sig, stop.set)
        except (NotImplementedError, RuntimeError):
            pass

    workers: list[asyncio.Task[None]] = []
    spawn_delay = 1.0 / rate

    async def launcher() -> None:
        for idx in range(count):
            if stop.is_set():
                return
            workers.append(
                asyncio.create_task(
                    tcp_worker(idx, host, port, timeout, reconnect, stop, counters)
                )
            )
            await asyncio.sleep(spawn_delay)

    launcher_task = asyncio.create_task(launcher())

    try:
        while not stop.is_set():
            elapsed = time.monotonic() - started
            if elapsed >= duration:
                stop.set()
                break

            rss = read_rss_mb(args.pid)
            log_offset, new_errors = read_new_log_errors(args.log, log_offset)
            errors.extend(new_errors)
            samples.append(
                Sample(
                    elapsed_seconds=round(elapsed, 3),
                    active_connections=counters.active,
                    rss_mb=round(rss, 3) if rss is not None else None,
                )
            )
            await asyncio.sleep(sample_interval)
    finally:
        stop.set()
        await asyncio.gather(launcher_task, return_exceptions=True)
        await asyncio.gather(*workers, return_exceptions=True)

    elapsed = time.monotonic() - started
    rss_end = read_rss_mb(args.pid)
    rss_growth = (
        rss_end - rss_start
        if rss_start is not None and rss_end is not None
        else None
    )

    connect_failure_ratio = counters.connect_failures / max(counters.attempts, 1)
    disconnect_ratio = counters.unexpected_disconnects / max(counters.connected, 1)

    gates: dict[str, dict[str, Any]] = {}

    def gate(name: str, value: float | int | None, limit: float | int, ok: bool) -> None:
        gates[name] = {"value": value, "limit": limit, "pass": ok}

    max_connect_failure_ratio = float(limits.get("max_connect_failure_ratio", 1.0))
    max_disconnect_ratio = float(limits.get("max_unexpected_disconnect_ratio", 1.0))
    max_rss_growth = float(limits.get("max_process_rss_growth_mb", float("inf")))
    max_errors = int(limits.get("max_error_lines", 0))

    gate(
        "connect_failure_ratio",
        round(connect_failure_ratio, 6),
        max_connect_failure_ratio,
        connect_failure_ratio <= max_connect_failure_ratio,
    )
    gate(
        "unexpected_disconnect_ratio",
        round(disconnect_ratio, 6),
        max_disconnect_ratio,
        disconnect_ratio <= max_disconnect_ratio,
    )
    gate("error_lines", len(errors), max_errors, len(errors) <= max_errors)
    if rss_growth is not None:
        gate(
            "rss_growth_mb",
            round(rss_growth, 3),
            max_rss_growth,
            rss_growth <= max_rss_growth,
        )

    passed = all(item["pass"] for item in gates.values())
    result = Result(
        scenario=args.scenario,
        started_at=started_wall,
        duration_seconds=round(elapsed, 3),
        target=f"{host}:{port}",
        counters=counters,
        samples=samples,
        rss_start_mb=round(rss_start, 3) if rss_start is not None else None,
        rss_end_mb=round(rss_end, 3) if rss_end is not None else None,
        rss_growth_mb=round(rss_growth, 3) if rss_growth is not None else None,
        error_lines=errors[-200:],
        gates=gates,
        passed=passed,
    )

    args.report_dir.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    report_path = args.report_dir / f"{args.scenario}-{stamp}.json"
    report_path.write_text(json.dumps(asdict(result), indent=2), encoding="utf-8")

    print(f"Scenario : {args.scenario}")
    print(f"Target   : {host}:{port}")
    print(f"Duration : {elapsed:.1f}s")
    print(f"Attempts : {counters.attempts}")
    print(f"Connected: {counters.connected} (peak {counters.peak_active})")
    print(f"Failures : {counters.connect_failures}")
    print(f"Drops    : {counters.unexpected_disconnects}")
    if rss_growth is not None:
        print(f"RSS      : {rss_start:.1f} -> {rss_end:.1f} MB ({rss_growth:+.1f} MB)")
    print(f"Errors   : {len(errors)}")
    print(f"Report   : {report_path}")
    print("RESULT   : " + ("PASS" if passed else "FAIL"))
    return 0 if passed else 1


def parse_args() -> argparse.Namespace:
    root = Path(__file__).resolve().parent
    parser = argparse.ArgumentParser(description="Cardboard post-release torture harness")
    parser.add_argument("scenario", choices=("smoke", "burst", "soak"))
    parser.add_argument("--config", type=Path, default=root / "scenarios.toml")
    parser.add_argument("--host")
    parser.add_argument("--port", type=int)
    parser.add_argument("--duration", type=float)
    parser.add_argument("--connections", type=int)
    parser.add_argument("--rate", type=float)
    parser.add_argument("--pid", type=int, help="Minecraft server PID; Linux /proc RSS sampling")
    parser.add_argument("--log", type=Path, help="latest.log path; only new lines are scanned")
    parser.add_argument("--report-dir", type=Path, default=root / "reports")
    return parser.parse_args()


def main() -> int:
    if sys.version_info < (3, 11):
        print("Python 3.11+ is required (tomllib).", file=sys.stderr)
        return 2
    try:
        return asyncio.run(run(parse_args()))
    except KeyboardInterrupt:
        return 130


if __name__ == "__main__":
    raise SystemExit(main())
